#ifndef PARAMETERS_H
#define PARAMETERS_H

#define WINDOW_SIZE_X 1200
#define WINDOW_SIZE_Y 600

#define SNAKE_CIRCLE_RADIUS 10
#define FOOD_CIRCLE_RADIUS 5

#define FOOD_PROBA 0.01
#define ADD_TAIL 4

#define INIT_LENGTH 4

#define LOW_SPEED 2
#define HIGH_SPEED 4
#define ROTATION_ANGLE 0.02

#define EPSILON 0.01

#endif
